apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-backend-pvc
  namespace: logging
  labels:
    app.kubernetes.io/name: logging-backend
    app.kubernetes.io/app: logging-backend
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
