---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fb-fluent-bit
  namespace: logging
  labels:
    helm.sh/chart: fluent-bit-0.52.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fb
    app.kubernetes.io/version: "4.0.7"
    app.kubernetes.io/managed-by: Helm
---
# Source: fluent-bit/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-fluent-bit
  namespace: logging
  labels:
    helm.sh/chart: fluent-bit-0.52.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fb
    app.kubernetes.io/version: "4.0.7"
    app.kubernetes.io/managed-by: Helm
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        # Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
    
    [INPUT]
        Name              tail
        Path              /var/log/containers/*_dev-aiagent_*.log
        Exclude_Path      /var/log/containers/*fluent-bit*.log
        Tag               kube.*
        multiline.parser  docker, cri
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    
    # (선택) kubelet systemd 로그 - 비활성화
    #[INPUT]
    #    Name            systemd
    #    Tag             host.*
    #    Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
    #    Read_From_Tail  On
    
    [FILTER]
        Name                  kubernetes
        Match                 kube.*
        Merge_Log             On
        Keep_Log              Off
        K8S-Logging.Parser    On
        K8S-Logging.Exclude   On
        Annotations           Off
        Labels                Off
    
    # logging-backend로 HTTP POST 전송
    [OUTPUT]
        Name          http
        Match         kube.*
        Host          logging-backend-service.logging
        Port          8080
        URI           /logs
        Format        json
        Header        Content-Type application/json
    # 1단계: stdout로 보기 (줄바꿈/들여쓰기)
    [OUTPUT]
        Name   stdout
        Match  *
        Format json_pretty
    
    # 2단계: 예시) Elasticsearch 전환 시 주석 해제
    # [OUTPUT]
    #     Name            es
    #     Match           kube.*
    #     Host            elasticsearch-master.logging.svc
    #     Port            9200
    #     Logstash_Format On
    #     Retry_Limit     False
---
# Source: fluent-bit/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fb-fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.52.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fb
    app.kubernetes.io/version: "4.0.7"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
---
# Source: fluent-bit/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fb-fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.52.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fb
    app.kubernetes.io/version: "4.0.7"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fb-fluent-bit
subjects:
  - kind: ServiceAccount
    name: fb-fluent-bit
    namespace: logging
---
# Source: fluent-bit/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fb-fluent-bit
  namespace: logging
  labels:
    helm.sh/chart: fluent-bit-0.52.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fb
    app.kubernetes.io/version: "4.0.7"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 2020
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fb
---
# Source: fluent-bit/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fb-fluent-bit
  namespace: logging
  labels:
    helm.sh/chart: fluent-bit-0.52.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fb
    app.kubernetes.io/version: "4.0.7"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/instance: fb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/instance: fb
      annotations:
        checksum/config: 8f7b1df8e025f319ac67d4ba607fd58140002584b900b5a1623356186fd4a514
        fluentbit.io/exclude: "true"
    spec:
      
      serviceAccountName: fb-fluent-bit
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
        - name: fluent-bit
          image: "cr.fluentbit.io/fluent/fluent-bit:4.0.7"
          imagePullPolicy: IfNotPresent
          command:
            - /fluent-bit/bin/fluent-bit
          args:
            - --workdir=/fluent-bit/etc
            - --config=/fluent-bit/etc/conf/fluent-bit.conf
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/conf
            - mountPath: /var/log
              name: varlog
      volumes:
        - name: config
          configMap:
            name: fb-fluent-bit
        - hostPath:
            path: /var/log
          name: varlog
      tolerations:
        - operator: Exists
---
# Source: fluent-bit/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "fb-fluent-bit-test-connection"
  namespace: logging
  labels:
    helm.sh/chart: fluent-bit-0.52.0
    app.kubernetes.io/version: "4.0.7"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  containers:
    - name: wget
      image: "busybox:latest"
      imagePullPolicy: Always
      command: ["sh"]
      args: ["-c", "sleep 5s && wget -O- fb-fluent-bit:2020"]
  restartPolicy: Never
